# Generated by Django 4.2.28 on 2026-02-06 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("license_key", models.CharField(max_length=50, unique=True)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("lifetime", "Lifetime"),
                            ("annual", "Annual"),
                            ("trial", "Trial"),
                        ],
                        default="lifetime",
                        max_length=20,
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_activated", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("activation_count", models.IntegerField(default=0)),
                (
                    "max_activations",
                    models.IntegerField(
                        default=1, help_text="Number of devices allowed"
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("customer_email", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("issued_by", models.CharField(default="EROM_SYSTEM", max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_id",
                    models.CharField(
                        help_text="Hardware fingerprint", max_length=200, unique=True
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=200)),
                (
                    "activation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivation_date", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="licensing.license",
                    ),
                ),
            ],
            options={
                "db_table": "license_activations",
                "ordering": ["-activation_date"],
            },
        ),
    ]
