# Generated by Django 4.2.28 on 2026-02-06 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or business registration",
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "area",
                    models.CharField(
                        blank=True, help_text="Working area/district", max_length=100
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=200)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum debt allowed (0 = unlimited)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=False,
                        help_text="Trusted agents have higher credit limits",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents_created",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agents",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="AgentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, help_text="Transaction reference", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="agents.agent",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_payments_received",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="agent_payme_agent_i_9c288d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount owed", max_digits=10
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("inventory_movement_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="agents.agent",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_transfers",
                        to="inventory.product",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_transfers",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_ledger",
                "ordering": ["-transfer_date"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-transfer_date"],
                        name="agent_ledge_agent_i_bccac4_idx",
                    ),
                    models.Index(
                        fields=["is_paid"], name="agent_ledge_is_paid_7d8c95_idx"
                    ),
                    models.Index(
                        fields=["transfer_date"], name="agent_ledge_transfe_fd82dc_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["phone_number"], name="agents_phone_n_6f1873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["is_active"], name="agents_is_acti_3fbec7_idx"),
        ),
    ]
