# Generated by Django 4.2.28 on 2026-02-06 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("license_key", models.CharField(max_length=100, unique=True)),
                (
                    "license_activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("license_expires_at", models.DateTimeField(blank=True, null=True)),
                ("device_id", models.CharField(max_length=200, unique=True)),
                ("max_devices", models.IntegerField(default=1)),
                ("currency", models.CharField(default="RWF", max_length=10)),
                ("timezone", models.CharField(default="Africa/Kigali", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shop Configuration",
                "verbose_name_plural": "Shop Configuration",
                "db_table": "shop_config",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("cashier", "Cashier/Manager")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("session_token", models.CharField(blank=True, max_length=100)),
                ("session_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
