# Generated by Django 4.2.28 on 2026-02-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("startup", "System Startup"),
                            ("shutdown", "System Shutdown"),
                            ("error", "System Error"),
                            ("migration", "Database Migration"),
                            ("update", "System Update"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="system_even_created_43439e_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="system_even_event_t_7f12a3_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="system_even_severit_8b827f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Backup"),
                            ("automatic", "Automatic Backup"),
                            ("before_update", "Pre-Update Backup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size_bytes", models.BigIntegerField()),
                (
                    "checksum",
                    models.CharField(help_text="SHA-256 checksum", max_length=64),
                ),
                ("is_encrypted", models.BooleanField(default=True)),
                (
                    "encryption_algorithm",
                    models.CharField(default="AES-256-GCM", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backups_created",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "backup_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("reversal", "Reversal"),
                            ("approval", "Approval"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Model class name", max_length=100),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True, help_text="State before action", null=True
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True, help_text="State after action", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_log_created_e49a79_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_log_user_id_b57afc_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_log_model_n_c04ad8_idx",
                    ),
                    models.Index(fields=["action"], name="audit_log_action_b32d4d_idx"),
                ],
            },
        ),
    ]
